baseURL = "https://nantipov.org/"
languageCode = "en-US"
title = "Engineer's notes"
theme = "bootstrap-bp-hugo-theme"
googleAnalytics = "UA-135023710-1"
disqusShortname = "nantipov-org"
copyright = "nantipov.org"
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "tango"
canonifyurls = true
paginate = 5

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[permalinks]
  posts = "/:year/:month/:slug/"
  post = "/:year/:month/:slug/"
  pages = "/:slug/"
  page = "/:slug/"

[Author]
  name = "Nikolai Antipov"

[params]
  description = "Notes I am putting not to forget"
  #images = ["logo.jpg"]
  showPostSummary = true
  startPageColumns = true
  # customDateFormat = "02.01.2006"

## Main Menu
[[menu.main]]
    name = "About"
    weight = 100
    identifier = "about"
    url = "/about"
[[menu.main]]
    name = "Posts RSS"
    weight = 300
    identifier = "rss"
    url = "/post/index.xml"
