baseURL = "https://nantipov.org/"
languageCode = "en-US"
title = "Engineer's notes"
theme = "zzo"

googleAnalytics = "UA-135023710-1"
enableRobotsTXT = true
canonifyurls = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = false

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

enableGitInfo = false


[sitemap]
  changefreq = "weekly"
  priority = 0.5

[permalinks]
  posts = "/:year/:month/:slug/"
  post = "/:year/:month/:slug/"
  pages = "/:slug/"
  page = "/:slug/"
[params]
  description = "Notes I am putting not to forget"
  #images = ["logo.jpg"]
  showPostSummary = true
  startPageColumns = true
  # customDateFormat = "02.01.2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2


[outputs]
  page = ["HTML", "SearchIndex"]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
